### ISSUE TITLE
target 阶段 transfer 出现异常，错误码 -12 creep.callDefender is not a function

### ISSUE THREAD

**Issue by 923132714** [LokiSharp/ScreepsScript#10]
https://github.com/923132714/ScreepsScript/issues/16

creep.callDefender专业这方法的实现给干没了？

**Comment by LokiSharp** [comment]
Fixed: https://github.com/LokiSharp/ScreepsScript/commit/6d9ef053104fc0b9d91c981f1be3bebd59b74faf
