### ISSUE TITLE
unit 数量调整异常

### ISSUE THREAD

**Issue by 923132714** [LokiSharp/ScreepsScript#13]
https://github.com/923132714/ScreepsScript/issues/15

当调整为负数且加上当前的数量小于MIN的情况会出现问题，当这种情况直接置为MIN就完事。。。

**Comment by LokiSharp** [comment]
Fixed: https://github.com/LokiSharp/ScreepsScript/commit/d86718155bc091655e6efe545c9c2f6a04477388
