### ISSUE TITLE
 内存中的 workerNumber 以及 transporterNumber 并不符合实际情况，导致creep数量问题

### ISSUE THREAD

**Issue by 923132714** [LokiSharp/ScreepsScript#6]
问题位置: `src\modules\room\spawn\CreepRelease.ts`
![image](https://user-images.githubusercontent.com/25949545/115954808-89405600-a525-11eb-8c68-4b9c6424162b.png)

https://github.com/923132714/ScreepsScript/issues/12

**Comment by LokiSharp** [comment]
我感觉没必要每次都遍历一遍所有 Creep，正常情况下不会断代

**Comment by 923132714** [comment]
就是如果遇到就手动解决呗
